base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    tokenizer_mode: slow
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        # Available options: ['gemm_pack', 'gemv_pack']
        pack_version: gemm_pack
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
    inference_per_block: False
save:
    save_autoawq: True
    save_path: /path/to/save_for_autoawq_rtn_w4/
