base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: model_path
    tokenizer_mode: fast
    torch_dtype: torch.float8_e4m3fn
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_vllm: True
    save_path: /path/to/save/
