name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.head_ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit hook
        run: |
          pip install pre-commit==3.8.0 mmengine
          pre-commit install

      - name: Linting
        run: pre-commit run --all-files
