base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [transformed]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
sparse:
    method: Magnitude
    weight:
        sparsity: 0.5
save:
    save_trans: False
    save_path: ./save
