base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/gongoubo/checkpoints/Qwen/Qwen3-4B
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: True
    path: calib data path
    n_samples: 256
    bs: -1
    seq_len: 2048
    preproc: pileval_awq
    seed: *seed
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
    special:
        trans: True
        # The options for "trans_version" include "v1" and "v2".
        # But their results don't differ significantly.
        trans_version: v2
        weight_clip: True
        # For 2-bit quantization, setting "clip_sym: False" will yield better results.
        clip_sym: True
save:
    save_trans: False
    save_fake: False
    save_vllm: True
    save_path: /data/gongoubo/checkpoints/Qwen/Qwen3-4B-awq-w4a16
