base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/gongoubo/other_project/EfficientQAT/output/block_ap_models/qwen3-4b-w4g128-e2e-fake
    tokenizer_mode: slow
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        pack_version: gemm_pack
save:
    save_autoawq: True
    save_path: /data/gongoubo/other_project/EfficientQAT/output/block_ap_models/qwen3-4b-w4g128-e2e-rtn
