base:
    seed: &seed 42
model:
    type: Qwen2
    path: /data/gongoubo/checkpoints/Qwen/Qwen3-4B
    torch_dtype: auto
calib:
    name: pileval
    download: True
    path: calib data path
    n_samples: 256
    bs: 1
    seq_len: 2048
    preproc: txt_general_preproc
    seed: *seed
quant:
    method: SmoothQuant
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
    special:
        alpha: 0.8
save:
    save_trans: False
    save_fake: False
    save_path: /data/gongoubo/checkpoints/Qwen/Qwen3-4B-smoothquant-w4a16
