base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    torch_dtype: auto
eval:
    eval_pos: [transformed, fake_quant, fake_quant_wo_kv] #decode_ppl eval not support pretrain eval pos
    name: wikitext2
    type: decode_ppl
    download: False
    path: eval_data_path
    bs: 1
    inference_per_block: False
    num_samples: 50
    # num_eval_tokens: 3
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    kvcache:
        method: Kivi
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_fake: False
    save_path: /path/to/save/
