base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Awq
    weight:
        quant_type: float-quant
        bit: e2m1
        symmetric: False
        granularity: per_group
        group_size: 128
        use_qtorch: True
    special:
        quant_type: float-quant
        trans: True
        # The options for "trans_version" include "v1" and "v2".
        trans_version: v2
        weight_clip: True
        # For 2-bit quantization, setting "clip_sym: False" will yield better results.
        clip_sym: True
save:
    save_trans: False
    save_fake: False
    save_path: /path/to/save/
