base:
    seed: &seed 0
model:
    type: model_type
    path: model path
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: vlm_datastes
    type: img_txt
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: vlm_general
    padding: True
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant]
    type: vqa
    name: mme
    download: False
    path: MME dataset path
    bs: 1
    inference_per_block: False
quant:
    method: GPTQ
    quant_objects: [vision, language] # default is [language]
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        # calib_algo: mse
        # mse_b_num: 2
    special:
        actorder: True
        static_groups: False
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
save:
    save_fake: False
    save_path: /path/to/save/
